### ISSUE TITLE
Timed out waiting for crypto sequence 2

### ISSUE THREAD

**Issue by lprhodes** [edc1591/node-appletv#1]
Hey,

Great plugin, thanks!

I'm struggling to get through the "Initiating Pairing" stage due to the error message "Timed out waiting for crypto sequence 2" showing.

Any ideas?

**Comment by lprhodes** [comment]
Some more info:

- I'm running it on macOS.
- My Mac is able to pair with the Apple TV
- My iPhone is able to pair with the Apple TV.
- `device.on('message')` of the `waitForSequence` method is not called
- Increasing the timeout doesn't help

**Comment by lprhodes** [comment]
tlv_1.default.Tag.PairingMethod = 0
tlv_1.default.Tag.Sequence = 6

**Comment by lprhodes** [comment]
Another note; the pairing code appears on the Apple TV.

Here's the logs:

⠋ Connecting to LoungeDEBUG: >>>> Send Data=080f122437626339396239322d396631382d343836652d613766382d3532666130316262653234372000a201610a2435653566646432342d333538382d343036332d393465622d666336633837666236613234120c6e6f64652d6170706c6574761a066950686f6e65220531344736302a12636f6d2e6170706c652e545652656d6f746532063237332e31323801
DEBUG: >>>> Send Protobuf={
  "type": "DEVICE_INFO_MESSAGE",
  "identifier": "7bc99b92-9f18-486e-a7f8-52fa01bbe247",
  "priority": 0,
  ".deviceInfoMessage": {
    "uniqueIdentifier": "5e5fdd24-3588-4063-94eb-fc6c87fb6a24",
    "name": "node-appletv",
    "localizedModelName": "iPhone",
    "systemBuildVersion": "14G60",
    "applicationBundleIdentifier": "com.apple.TVRemote",
    "applicationBundleVersion": "273.12",
    "protocolVersion": 1
  }
}
DEBUG: <<<< Received Data=080f122437626339396239322d396631382d343836652d613766382d3532666130316262653234372000a201bb010a2443373344373432412d444135412d343338342d424441442d46353039324632343036313712064c6f756e6765220831354c35323131622a16636f6d2e6170706c652e6d6564696172656d6f7465643801403e480150016211636f6d2e6170706c652e54564d757369636801700178018801029a012431383639343536422d343643342d343245432d423736352d343437304431423831373136a2011163383a36393a63643a34353a65303a3562a80104b00101b80100c00100
DEBUG: <<<< Received Protobuf={
  "type": "DEVICE_INFO_MESSAGE",
  "identifier": "7bc99b92-9f18-486e-a7f8-52fa01bbe247",
  "priority": 0,
  ".deviceInfoMessage": {
    "uniqueIdentifier": "C73D742A-DA5A-4384-BDAD-F5092F240617",
    "name": "Lounge",
    "systemBuildVersion": "15L5211b",
    "applicationBundleIdentifier": "com.apple.mediaremoted",
    "protocolVersion": 1
  }
}
✔ Connecting to Lounge
⠋ Initiating PairingDEBUG: >>>> Send Data=08222000ba020a0a060001000601011000
DEBUG: >>>> Send Protobuf={
  "type": "CRYPTO_PAIRING_MESSAGE",
  "priority": 0,
  ".cryptoPairingMessage": {
    "pairingData": "AAEABgEB",
    "status": 0
  }
}
✖ Initiating Pairing
Timed out waiting for crypto sequence 2
Error: Timed out waiting for crypto sequence 2
    at Timeout.setTimeout [as _onTimeout] (/usr/local/lib/node_modules/node-appletv/dist/lib/pairing.js:128:24)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:267:5)

**Comment by edc1591** [comment]
Try rebooting your Apple TV and give it another try.

**Comment by lprhodes** [comment]
I’m running the beta too - it could be it but my Mac and iPhone are not running betas so their pairing mechanisms haven’t changed.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by edc1591** [comment]
I'll upgrade to 11.3 and give it a try.

**Comment by lprhodes** [comment]
I've downgraded to 11.2 and can confirm it works.

**Comment by edc1591** [comment]
Thanks for testing. I'm going to update to tvOS 11.3 this weekend and try to get it working.

**Comment by foldericon** [comment]
https://github.com/marcklefter/node-appletv-pairing works with 11.3

**Comment by edc1591** [comment]
Fixed in [1.0.5](https://github.com/edc1591/node-appletv/releases/tag/1.0.5)
