### ISSUE TITLE
DeviceInfoUpdate.proto missing

### ISSUE THREAD

**Issue by lprhodes** [edc1591/node-appletv#3]
Hi,

I'm receiving the message `Error: ENOENT: no such file or directory, open '/Users/rhodesy22/Dev/homebridge-apple-tv/node_modules/node-appletv/dist/lib/protos/DeviceInfoUpdate.proto'` when putting the Apple TV to sleep.

Thanks

**Comment by edc1591** [comment]
Fixed in [1.0.7](../releases/1.0.7).
